:bug: :snake: can't install .whl file with wrong name
Error: buildx bake failed with: error: failed to solve:

process "/bin/sh -c pip install /tmp/cog.whl" did not complete successfully: exit code: 1

https://github.com/marcellodesales/replicated-cog-server-docker/runs/4848187349?check_suite_focus=true

Not sure why, but does it need to be full name? Why?